### PR TITLE
remove 'at' rules

### PR DESCRIPTION
**Pull request by mimi1vx**
Ati driver's repository don't exist anymore

### CODE REVIEW

**Comment by mimi1vx** [comment]
@hrommel  please check

**Comment by plusky** [comment]
Indeed there does not seem any trace of ati repositories for SUSE on ati/amd sites.

**Comment by plusky** [comment]
Hmm not only is ati url dead but it seems that smt/scc offer only nvidia repositoris - I can not but wonder how long is it since ati repos worked.

**Comment by plusky** [comment]
Interestingly `wget http://www2.ati.com/suse/sle12/repodata/repomd.xml` will fetch correct metadata, so only directory listing is disabled. Afaik we should drop this request and instead update documentation so that others are not confused in future.

**Comment by mimi1vx** [comment]
@plusky  I agree with drop this request , but this reveal small problem in test-online , we must change target of this test

not needed any other change in docu

**Pull request closed without merging**
